// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdp1rIJ74Lrrh859GzmEqHjvyS-7Vnky8',
    appId: '1:527380473232:web:b398a47410bd14106fff15',
    messagingSenderId: '527380473232',
    projectId: 'firstapp-9dc95',
    authDomain: 'firstapp-9dc95.firebaseapp.com',
    databaseURL: 'https://firstapp-9dc95-default-rtdb.firebaseio.com',
    storageBucket: 'firstapp-9dc95.appspot.com',
    measurementId: 'G-WM595NJK9N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9AaVL8LaXYMiPEC2HFt39-otc1PzYXT0',
    appId: '1:527380473232:ios:fc3c8159a09233806fff15',
    messagingSenderId: '527380473232',
    projectId: 'firstapp-9dc95',
    databaseURL: 'https://firstapp-9dc95-default-rtdb.firebaseio.com',
    storageBucket: 'firstapp-9dc95.appspot.com',
    iosBundleId: 'com.xgenious.gocar',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHb77420sCbMSr4tzh0Y8lCLD4BZgbD5w',
    appId: '1:527380473232:android:543d21e329e8e81a6fff15',
    messagingSenderId: '527380473232',
    projectId: 'firstapp-9dc95',
    databaseURL: 'https://firstapp-9dc95-default-rtdb.firebaseio.com',
    storageBucket: 'firstapp-9dc95.appspot.com',
  );

}