// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYMuu0kwONipsywsd3iJ9kwZhoYtTlN6s',
    appId: '1:423970134410:web:cb31cdc5329c9ed98d5073',
    messagingSenderId: '423970134410',
    projectId: 'jusmoto-app',
    authDomain: 'jusmoto-app.firebaseapp.com',
    storageBucket: 'jusmoto-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSGwnhnpmQ28wdjFjeTwoeWtILma6VXgE',
    appId: '1:423970134410:android:677d681316ee20e48d5073',
    messagingSenderId: '423970134410',
    projectId: 'jusmoto-app',
    storageBucket: 'jusmoto-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACp-UYJR_YpoFtESvCb-XUyQ584_R_T5w',
    appId: '1:423970134410:ios:0f82da1e1aedf0ea8d5073',
    messagingSenderId: '423970134410',
    projectId: 'jusmoto-app',
    storageBucket: 'jusmoto-app.firebasestorage.app',
    iosClientId: '423970134410-5v9nq9hv31kfei7nhqb79bgoledf6f5c.apps.googleusercontent.com',
    iosBundleId: 'com.xgenious.gocar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACp-UYJR_YpoFtESvCb-XUyQ584_R_T5w',
    appId: '1:423970134410:ios:0754a978731b75dc8d5073',
    messagingSenderId: '423970134410',
    projectId: 'jusmoto-app',
    storageBucket: 'jusmoto-app.firebasestorage.app',
    iosClientId: '423970134410-0fq8rcmt3j6i88usa9jkvppbqgvbg87n.apps.googleusercontent.com',
    iosBundleId: 'com.example.carService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYMuu0kwONipsywsd3iJ9kwZhoYtTlN6s',
    appId: '1:423970134410:web:1c8d063cb3f731398d5073',
    messagingSenderId: '423970134410',
    projectId: 'jusmoto-app',
    authDomain: 'jusmoto-app.firebaseapp.com',
    storageBucket: 'jusmoto-app.firebasestorage.app',
  );
}
